package com.barchart.feed.api.series;


public enum CorporateAction {
	ASSIMILATION, 
	ATTACHMENT, 
	BANKRUPTCIES, 
	BONUS_ISSUE, 
	BONUS_RIGHTS, 
	CALLS, 
	CAPITALIZATION, 
	DIVIDENDS,
	CASH_DISTRIBUTIONS,
	CHANGE,
	CONSENTS, 
	CONVERTIBLE_SECURITY_ISSUE,
	DEFAULT,
	MEETING,
	MERGER,
	REORGANIZATION,
	STOCK_SPLITS,
	SECURITY_SEPARATION,
	SPINOFF,
	SUBSCRIPTION_OFFER,
	RIGHTS_ISSUE,
	WARRANTS_ISSUE,
	ODD_LOT_OFFER,
	DUTCH_AUCTION,
	TENDER_OFFERS,
	TERMINATION
}